import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AuthProvider from "@/providers/auth-provider";
import CartProvider from "@/providers/cart-provider";
import ThemeProvider from "@/providers/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "@/libraries/di/reflect-metadata";
import "@/app/globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME || "Next App",
  description:
    process.env.NEXT_PUBLIC_APP_DESCRIPTION || "Generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthProvider>
          <ThemeProvider>
            <CartProvider>
              <Header />
              {children}
              <Footer />
            </CartProvider>
          </ThemeProvider>
        </AuthProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
